version: "3"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynetwork
  jenkins:
    image: jenkins/jenkins:2.414.2-jdk17
    ports:
      - 8888:8080
    networks:
      - mynetwork
networks:
  mynetwork: