package com.epam.project.exceptions.enums;

public enum Code {
    REQUEST_VALIDATION_ERROR,
    STATUS_VALIDATION_ERROR,
    NICKNAME_BUSY,
    INTERNAL_SERVER_ERROR,
    USER_NOT_FOUND,
    USER_NAME_EXISTS,
    NULL_NOT_ALLOWED,
    AUTHORIZATION_ERROR,
    ARGUMENT_TYPE_MISMATCH,
    NOT_SUPPORTED,
    NOT_YOUR_COMMENT,
    BLOCKED,
    BAD_REQUEST
}
